#include <string>

enum class AccountType {
    DEBIT,
    DEPOSIT,
    CREDIT
};

enum class Currency {
    RUB,
    YUAN,
    USD,
    EUR
};

enum class DepositType {
    COMPOUNDED_DAILY_REMAINING,
    COMPOUNDED_DAILY_MIN,
    COMPOUNDED_MONTHLY_REMAINING,
    COMPOUNDED_MONTHLY_MIN,
    COMPOUNDED_QUARTERLY_REMAINING,
    COMPOUNDED_QUARTERLY_MIN,
    COMPOUNDED_SEMI_ANNUALLY_REMAINING,
    COMPOUNDED_SEMI_ANNUALLY_MIN,
    COMPOUNDED_ANNUALLY_REMAINING,
    COMPOUNDED_ANNUALLY_MIN
};

enum class CreditType {
    CHARGED_DAILY,
    CHARGED_MONTHLY,
    CHARGED_QUARTERLY,
    CHARGED_SEMI_ANNUALLY,
    CHARGED_ANNUALLY
};

enum class ClientType {
    INDIVIDUAL,
    LEGAL_ENTITY,
    VIP_INDIVIDUAL,
    VIP_LEGAL_ENTITY,
    NOT_A_CLIENT
};

enum class WorkplaceType {
    CLIENT_MANAGER,
    CASH_DESK,
    CURRENCY_EXCHANGE,
    VIP_CLIENT_MANAGER
};
